# Generated by Django 4.2.1 on 2023-12-16 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Knearest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first", models.IntegerField(blank=True, null=True)),
                ("second", models.IntegerField(blank=True, null=True)),
                ("third", models.IntegerField(blank=True, null=True)),
                ("fourth", models.IntegerField(blank=True, null=True)),
                ("fifth", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "knearest",
            },
        ),
        migrations.CreateModel(
            name="NewsArticle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, null=True)),
                ("author", models.CharField(max_length=100, null=True)),
                ("pub_date", models.DateTimeField(null=True)),
                ("content", models.TextField(null=True)),
                ("keywords", models.TextField(null=True)),
            ],
            options={
                "db_table": "news_article",
            },
        ),
        migrations.CreateModel(
            name="Postings",
            fields=[
                (
                    "term",
                    models.TextField(blank=True, primary_key=True, serialize=False),
                ),
                ("df", models.IntegerField(blank=True, null=True)),
                ("docs", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "postings",
            },
        ),
        migrations.CreateModel(
            name="Users",
            fields=[
                ("user_id", models.AutoField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=100)),
                ("password", models.CharField(max_length=100)),
                ("firstname", models.CharField(max_length=100)),
                ("lastname", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "users",
            },
        ),
    ]
