# Generated by Django 4.2.1 on 2023-12-07 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App0", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsArticle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("author", models.CharField(max_length=100)),
                ("pub_date", models.DateTimeField()),
                ("content", models.TextField()),
                ("keywords", models.TextField()),
            ],
            options={
                "db_table": "news_article",
            },
        ),
    ]
