# Generated by Django 4.2.1 on 2023-12-22 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App0", "0003_userinfo_searchhistory"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsArticle1",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, null=True)),
                ("url", models.CharField(max_length=200, null=True)),
                ("pub_date", models.DateTimeField(null=True)),
                ("content", models.TextField(null=True)),
                ("snapshot", models.TextField(blank=True, null=True)),
                ("pagerank_score", models.FloatField(default=0.0)),
                (
                    "linked_articles",
                    models.ManyToManyField(blank=True, to="App0.newsarticle1"),
                ),
            ],
            options={
                "db_table": "news_article1",
            },
        ),
    ]
