# Generated by Django 4.2.1 on 2023-12-23 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App0", "0004_newsarticle1"),
    ]

    operations = [
        migrations.CreateModel(
            name="Postings1",
            fields=[
                (
                    "term",
                    models.TextField(blank=True, primary_key=True, serialize=False),
                ),
                ("df", models.IntegerField(blank=True, null=True)),
                ("docs", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "postings1",
            },
        ),
        migrations.AddField(
            model_name="newsarticle",
            name="news_id",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="newsarticle1",
            name="news_id",
            field=models.IntegerField(default=0),
        ),
    ]
