# Generated by Django 4.2.1 on 2023-12-27 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App0", "0006_newsarticle1_keywords"),
    ]

    operations = [
        migrations.AddField(
            model_name="newsarticle1",
            name="category",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
